language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo

addons:
  apt:
    packages:
      - libssl-dev

env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=x86_64-unknown-linux-musl
  - TARGET=aarch64-unknown-linux-gnu
  - TARGET=aarch64-unknown-linux-musl
  - TARGET=armv7-unknown-linux-gnueabi
  - TARGET=armv7-unknown-linux-musleabi
  - TARGET=armv7-unknown-linux-gnueabihf
  - TARGET=armv7-unknown-linux-musleabihf
  - TARGET=x86_64-unknown-freebsd
  - TARGET=x86_64-unknown-netbsd

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: osx
      rust: beta
      env: TARGET=x86_64-apple-darwin
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin

install:
  - rustup target install "$TARGET"
  - if [[ "$TRAVIS_RUST_VERSION" == stable ]] && [[ "$TARGET" == x86_64-unknown-linux-gnu ]]; then COVERAGE=true; fi
  - if [[ "$COVERAGE" == true ]]; then cargo install cargo-tarpaulin; fi

script:
  - cargo build --verbose --target="$TARGET"
  - case "$TRAVIS_OS_NAME-$TARGET" in linux-x86_64-unknown-linux-*|osx-x86_64-apple-darwin) cargo test --verbose --target="$TARGET";; esac
  - if [[ "$COVERAGE" == true ]]; then cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash); fi
