language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=x86_64-unknown-linux-musl
  - TARGET=aarch64-unknown-linux-gnu
  - TARGET=aarch64-unknown-linux-musl
  - TARGET=armv7-unknown-linux-gnueabi
  - TARGET=armv7-unknown-linux-musleabi
  - TARGET=armv7-unknown-linux-gnueabihf
  - TARGET=armv7-unknown-linux-musleabihf
  - TARGET=x86_64-unknown-freebsd
  - TARGET=x86_64-unknown-netbsd

jobs:
  include:
    - os: osx
      rust:
        - stable
        - beta
        - nightly
      env: TARGET=x86_64-apple-darwin

install:
  - rustup target install "$TARGET"

script:
  - cargo build --verbose --target="$TARGET"
  - case "$TRAVIS_OS_NAME-$TARGET" in linux-x86_64-unknown-linux-*|osx-x86_64-apple-darwin) cargo test --verbose --target="$TARGET";; esac
