language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo

addons:
  apt:
    packages:
      - libssl-dev

os: linux
dist: bionic

env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=x86_64-unknown-linux-musl
  - TARGET=aarch64-unknown-linux-gnu
  - TARGET=aarch64-unknown-linux-musl
  - TARGET=armv7-unknown-linux-gnueabi
  - TARGET=armv7-unknown-linux-musleabi
  - TARGET=armv7-unknown-linux-gnueabihf
  - TARGET=armv7-unknown-linux-musleabihf
  - TARGET=x86_64-unknown-freebsd
  - TARGET=x86_64-unknown-netbsd

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

  include:
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: osx
      rust: beta
      env: TARGET=x86_64-apple-darwin
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin

install:
  - rustup target install "$TARGET"
  - case "$TRAVIS_OS_NAME-$TARGET" in linux-x86_64-unknown-linux-*|osx-x86_64-apple-darwin) TEST=true;; esac
  - if [[ "$TRAVIS_RUST_VERSION-$TARGET" == stable-x86_64-unknown-linux-* ]] && [[ "$TEST" == true ]]; then COVERAGE=true; COVERAGE_TARPAULIN=true; fi
  - if [[ "$TRAVIS_RUST_VERSION-$TARGET" == nightly-x86_64-apple-darwin ]] && [[ "$TEST" == true ]]; then COVERAGE=true; COVERAGE_GRCOV=true; fi
  - if [[ "$COVERAGE_TARPAULIN" == true ]]; then cargo install cargo-tarpaulin; fi
  - |
    if [[ "$COVERAGE_GRCOV" == true ]]; then
      # Based off of https://github.com/mozilla/grcov#grcov-with-travis
      export CARGO_INCREMENTAL=0
      export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
      export RUSTDOCFLAGS="-Cpanic=abort"
      curl -L "https://github.com/mozilla/grcov/releases/latest/download/grcov-$TRAVIS_OS_NAME-x86_64.tar.bz2" | tar jxf -
    fi

script:
  - cargo build --verbose --target="$TARGET"
  - if [[ "$TEST" == true ]]; then cargo test --verbose --target="$TARGET"; fi
  - if [[ "$TEST" == true ]]; then cargo test --verbose --target="$TARGET" --no-default-features; fi
  - if [[ "$COVERAGE_TARPAULIN" == true ]]; then cargo tarpaulin --out Xml; fi
  # Based off of https://github.com/mozilla/grcov#grcov-with-travis
  - if [[ "$COVERAGE_GRCOV" == true ]]; then zip -0 ccov.zip `find . \( -name "simple_libc*.gc*" \) -print`; ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info; fi
  - if [[ "$COVERAGE" == true ]]; then bash <(curl -s https://codecov.io/bash); fi
