language: rust
rust:
  - stable
  - beta
  - nightly

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

jobs:
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      env: TARGET=aarch64-unknown-linux-gnu
    - os: linux
      env: TARGET=aarch64-unknown-linux-musl
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabi
    - os: linux
      env: TARGET=armv7-unknown-linux-musleabi
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
    - os: linux
      env: TARGET=armv7-unknown-linux-musleabihf
    - os: linux
      env: TARGET=x86_64-unknown-freebsd
    - os: linux
      env: TARGET=x86_64-unknown-netbsd
    - os: osx
      env: TARGET=x86_64-apple-darwin

install:
  - rustup target install "$TARGET"

script:
  - cargo build --verbose --target="$TARGET"
  - case "$TRAVIS_OS_NAME-$TARGET" in linux-x86_64-unknown-linux-*|osx-x86_64-apple-darwin) cargo test --verbose --target="$TARGET";; esac
